### PR TITLE
Ensure `connect` only fulfills once all requested triggers are ready

### LINKED ISSUE #2: `connect()` can fulfill without ever having connected successfully
My application startup looks roughly like
```js
  console.log('Initializing pubSub...');
  await pubSubInstance.connect();
  console.log('Initialized!');
  await startServer();
```

I was surprised to find that when Postgres was offline, my application logs looked like this:
```
Initializing pubSub...
  pg-listen:connection Creating PostgreSQL client for notification streaming +0ms
calling connect
Initialized!
  pg-listen:connection DB Client connection ended +18ms
  pg-listen:connection Reconnecting to PostgreSQL for notification streaming +2ms
  pg-listen:connection PostgreSQL reconnection attempt #1... +0ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +1ms
🚀  Server ready at http://localhost:4000/
  pg-listen:connection PostgreSQL reconnection attempt #2... +508ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +2ms
  pg-listen:connection PostgreSQL reconnection attempt #3... +506ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +2ms
  pg-listen:connection PostgreSQL reconnection attempt #4... +505ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +2ms
  pg-listen:connection PostgreSQL reconnection attempt #5... +505ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +2ms
  pg-listen:connection PostgreSQL reconnection attempt #6... +502ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +1ms
  pg-listen:connection Error: Re-initializing the PostgreSQL notification client after connection loss failed: Stopping PostgreSQL reconnection attempts after 3000ms timeout has been reached.
  pg-listen:connection     at /Users/ssw/code/api/node_modules/pg-listen/dist/index.js:108:47
  pg-listen:connection     at step (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:43:23)
  pg-listen:connection     at Object.next (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:24:53)
  pg-listen:connection     at step (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:28:139)
  pg-listen:connection     at Object.next (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:24:53)
  pg-listen:connection     at fulfilled (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:15:58) +502ms
```

Is it intended that `connect` can fulfill even when the underlying `pgListen` never connected to the database? It'd be more intuitive (to me) for `connect` to fulfill if and only if it successfully connects (after some number of retries).

A stopgap improvement may be to document what the correct way to await initial connection + listener establishment is. I might do something like
```js
await pubSub.connect();
// Then wait up to 3000 ms (or so) for `pubSub.connected` to become true.
// If it never does, abort.
``` 
since the `connected` boolean seems to be the only way to deduce that the listeners are established.

### PR DESCRIPTION
**Pull request by spencerwilson**
Fixes https://github.com/originlabs/graphql-postgres-subscriptions/issues/2

**Depends on https://github.com/originlabs/graphql-postgres-subscriptions/pull/4.**

Great news: All tests pass!

```
 PASS  ./postgres-pubsub.test.js
  PostgresPubSub
    ✓ PostgresPubSub can subscribe when instantiated without a client (10 ms)
    ✓ PostgresPubSub can subscribe and is called when events happen (7 ms)
    ✓ PostgresPubSub can subscribe when instantiated with connection options but without a client (5 ms)
    ✓ PostgresPubSub can unsubscribe (5 ms)
    ✓ Should emit error when payload exceeds Postgres 8000 character limit (7 ms)
    ✓ AsyncIterator should expose valid asyncIterator for a specific event
    ✓ AsyncIterator should trigger event on asyncIterator when published (7 ms)
    ✓ AsyncIterator should not trigger event on asyncIterator when publishing other event (4 ms)
    ✓ AsyncIterator should register to multiple events (4 ms)
    ✓ AsyncIterator transforms messages using commonMessageHandler (7 ms)
    ✓ PostgresPubSub transforms messages using commonMessageHandler (4 ms)
    ✓ AsyncIterator should not trigger event on asyncIterator already returned (8 ms)

Test Suites: 1 passed, 1 total
Tests:       12 passed, 12 total
Snapshots:   0 total
Time:        0.48 s, estimated 1 s
Ran all test suites.
```

The `@returns` docstring is [TSDoc](https://tsdoc.org) syntax, which at least VS Code understands:
image

### CODE REVIEW

File: postgres-pubsub.js [hunk 1]
```diff
@@ -29,23 +29,44 @@ class PostgresPubSub extends PubSub {
...
+   *   2. pg-listen emits 'error', likely indicating initial connection failed
+   *      even after repeated attempts.
+   *   3. Connection to the database was successful, but at least one
+   *      `LISTEN` query failed.
+   *
+   * Fulfills otherwise, indicating all of the requested triggers are now being
+   * listened to.
+   */
+  connect() {
+    return new Promise(async (resolve, reject) => {
```
Comment (Jonahss) [inline postgres-pubsub.js]: A wise reviewer (@bendrucker) once told me that if you find yourself using the `Promise` constructor, in almost all cases it can be avoided. Promises may need to be created from scratch at the very base of a codebase, like if you were writing a library like lodash, but in most cases, if you're dealing with promises it's because they've been passed up to you. In that case, you can usually return them.

Can you find a way to keep `connect` as an `async` function, and still achieve the same functionality?

**Review by Jonahss — CHANGES_REQUESTED** [review]

**Comment by Jonahss** [comment]
One change requested. Also, I merged #4 so now there are conflicts.

File: postgres-pubsub.js (hunk 1 above)
Comment (spencerwilson) [reply postgres-pubsub.js]: Hrm, yeah, my first few attempts were actually `Promise.all`-based, which wasn't a great fit. `Promise.race` might work well, if I can codify the 4 possible fates of the promise that this function returns (as described in its docstring) in terms of 4 promises fed into `Promise.race`. I expect at least a couple of those constituent promises will have to be built with `new Promise`, though (e.g., the promise that ought to reject if `this.pgListen.events` ever emits an `'error'` event).

Will give it a shot. No guarantees that it'll be _simpler_ than this, though. 😬

Comment (spencerwilson) [reply postgres-pubsub.js]: Okeydoke, updated. Let me know if that feels better. I don't see a way to get rid of `new Promise` in places where we wish to have promise-y interfaces over events that are emitted. Anyway, let me know what you think and have a great weekend 😄

Comment (Jonahss) [reply postgres-pubsub.js]: I looked into it today and starting from your proposal here realized it's difficult to get around the event emitter without using the promise constructor >.< I don't think I was appreciating the difficulty of that in your first proposal.
I do like the `Promise.race` better now.

I'm submitting a PR to your PR where I did a quick refactor that made it a little easier to read for me. If you think that works, merge it, and then we'll merge this one :)

Thanks again for the help!

Comment (Jonahss) [reply postgres-pubsub.js]: Nvm, Github changed their UI. I'll merge this one and have you as a reviewer on my refactor.

**Review by Jonahss — APPROVED** [review]
